### ISSUE TITLE
Mantra architecture

### ISSUE THREAD

**Issue by lobosan** [themeteorchef/base#108]
Hi Chef, I was wondering if you are planning to use Mantra architecture and if so, what would be the difference between base and https://github.com/mantrajs/meteor-mantra-kickstarter

I'm currently using base but the loggin is a bit buggy sometimes, so I thought it might be a good idea to check the meteor guide in regards to user accounts http://guide.meteor.com/accounts.html

Any thoughts about this two options?

**Comment by themeteorchef** [comment]
I haven't looked into Mantra too much yet but no immediate plans to move to anything.

Re: login being buggy, is there something specific that's not working? If there is, can you file an issue for me with details on what isn't working? Will take a look at the guide to see how I can improve :)

**Comment by lobosan** [comment]
I see,

In regards to login being buggy, when I'm logged out in localhost but logged in in my meteor free server, when I visit my meteor version again, the login form appears instead of the default view. 
Another thing that happens is that when a user accepts an invitation, for few seconds the warning that the invite has been cancelled appears and then the form to provide the password. 
Lastly, sometimes when I've been developing with the console active, I've noticed a message related to a group variable not being recognized or something similar, if I see it again, I'll post the message.

Other than that everything is working well and thank you for your answer.

**Comment by themeteorchef** [comment]
> In regards to login being buggy, when I'm logged out in localhost but logged in in my meteor free server, when I visit my meteor version again, the login form appears instead of the default view. 

If I understand correctly this is expected. If you login and then leave the app, after some time you'll be required to login again. Following the recommended authentication pattern from Flow Router, instead of getting sent to `/login`, you will simply be shown the login template at whatever path you attempted to access (e.g., if you tried to go to /dashboard, you'd see the login form at that URL until you logged in).

See [my thoughts/conversation on this with the author of Flow Router](https://github.com/kadirahq/flow-router/issues/344).

> Another thing that happens is that when a user accepts an invitation, for few seconds the warning that the invite has been cancelled appears and then the form to provide the password. 

There isn't a feature for handling invitations built into Base (however a recipe has been written about this _using_ Base). Is the problem with the code from that recipe?

> Lastly, sometimes when I've been developing with the console active, I've noticed a message related to a group variable not being recognized or something similar, if I see it again, I'll post the message.

Sounds good. If/when you see it again, please file an issue for me :)

**Comment by lobosan** [comment]
I see thanks for the information. About the invitations you right, I added the code from that recipe.

And this is the error that I get sometimes:

![image](https://cloud.githubusercontent.com/assets/314886/12719188/a218ef52-c8c1-11e5-848b-e15b8406f96f.png)

The code is:
```
FlowRouter.notFound = {
  action() {
    BlazeLayout.render('default', {yield: 'notFound'});
  }
};

Accounts.onLogin(() => {
  let currentRoute = FlowRouter.current();
  if (currentRoute && currentRoute.route.group.name === 'public') {
    Modules.both.redirectUser();
  }
});

if (Meteor.isClient) {
  Tracker.autorun(() => {
    if (!Meteor.userId() && FlowRouter.current().route) {
      FlowRouter.go('login');
    }
  });
}
```

**Comment by themeteorchef** [comment]
@lobosan going to close this out here, can you open an issue on the recipe repo for me?

**Comment by lobosan** [comment]
Sure no problem
