### ISSUE TITLE
eslint-config-airbnb@7.0.0 requires a peer of eslint-plugin-jsx-a11y@^0.6.2

### ISSUE THREAD

**Issue by zeroasterisk** [themeteorchef/base#128]
```
npm WARN eslint-config-airbnb@7.0.0 requires a peer of eslint-plugin-jsx-a11y@^0.6.2 but none was installed.
```

should this be in the `package.json` ?

**Comment by themeteorchef** [comment]
Maybe.

Does adding `eslint-plugin-jsx-a11y` to `package.json` resolve this?

**Comment by zeroasterisk** [comment]
And... no it doesn't :/ sorry.

**Comment by themeteorchef** [comment]
@zeroasterisk it looks like this may do the trick (haven't tried yet):

![](http://cl.ly/3C2H2I3f1J0k/Image%202016-04-27%20at%209.25.42%20AM.png)

**Comment by slevr** [comment]
Although already closed, just thought I'd add that prior to seeing this issue and running into the same problem, I had resolved by simply adding: 
"eslint-plugin-jsx-a11y": "^0.6.2" 
to my devDependencies. This was after a clean install of Base 4. I did not have eslint installed globally, however, so that may still apply.
