### ISSUE TITLE
Why React-based

### ISSUE THREAD

**Issue by felipeuntill** [themeteorchef/base#169]
Can someone explain why base is currently React-based?

**Questions:**
- What i will gain using react instead of only meteor?
- React is an external framework and the meteorchef is the biggest reference about meteor. Using react in base maybe can make peoples think react is a requirement for meteor?
- Maybe is possible create a base without react?

**Comment by themeteorchef** [comment]
This choice was made due to the Meteor Development Group's decision to stop work on its own UI framework Blaze. Additionally, I realized that the React community/resource pool is far larger than Blaze and it made sense to leverage that as opposed to limit folks. Finally? I'm a personal fan of React and have found it keeps code organized and easy to understand. React is not a requirement for Meteor, just one of a few options for handling your UI.

Re: a version of Base without React, this has been discussed but I have no concrete plans for when I'd do it. If you'd like to see an early approach without React, check out any of the tags on this repo before 4.0.0.
