### ISSUE TITLE
Docs show "private" directory, doesn't appear in repo

### ISSUE THREAD

**Issue by davidrea** [themeteorchef/base#68]
In the Base documentation (http://themeteorchef.com/base/file-structure/) the file structure section shows a "private" directory meant to hold email templates - this isn't showing up in the repo...

**Comment by themeteorchef** [comment]
Howdy! This is a bit confusing. Because that folder is technically "empty" (it has a sub-folder but no files), Git strips it from the repo. So in this instance, if you'd like to follow that structural pattern you will need to add the directories _after_ you've cloned the repo. 

Until I add some templates in there, this will get lopped off unfortunately.

**Comment by darko-mijic** [comment]
Maybe you could add .gitkeep files in empty folders?

**Comment by josephdburdick** [comment]
I agree with @darko-mijic, this is how Iron-cli does it when it generates empty directories.

**Comment by themeteorchef** [comment]
Had no idea `.gitkeep` was a thing, this is great! Will review your PR @josephdburdick.

**Comment by josephdburdick** [comment]
Cool. :sunglasses:

**Comment by davidrea** [comment]
Ahh...I didn't realize the email templates directory was empty at present! Makes sense, and we got to learn about .gitkeep in the process! :) Thanks...
