### ISSUE TITLE
Flow router helpers

### ISSUE THREAD

**Issue by darko-mijic** [themeteorchef/base#74]
I was wondering why are you not using arillo/meteor-flow-router-helpers in base v3?
I ca see you wrote similar functionality in client/helpers/flow-router.js.

**Comment by themeteorchef** [comment]
Good question! Two reasons:

1.) Their helpers are written in CoffeeScript which made it a little more difficult to understand.
2.) Because implementing helpers separately is new (used to be provided by Iron Router), I wanted to make sure it was clear how this was working and why. 

The helpers you see are adapted from that package, just in JavaScript. Ultimately, it made more sense to make these accessible/customizable then to lock them up in a package.
